# Special workspaces
workspace = special:term, gapsout:300, layout:scrolling, layoutopt:direction:right, on-created-empty:$terminal
workspace = special:discord, gapsout:300 1200 300 1200, on-created-empty:discord
workspace = special:whatsapp, gapsout:300 1200 300 1200, on-created-empty:brave --app=https://web.whatsapp.com
workspace = special:teamspeak3, on-created-empty:teamspeak3
workspace = special:game

workspace = n[s:special:term]w[v1], gapsout:300 1200 300 1200, layout:scrolling, layoutopt:direction:right, on-created-empty:$terminal

# Assign windows to special workspaces
# "workspace w" versus "workspace:w" -> open in workspace versus only if in workspace
#windowrule = match:workspace special:term, match:class $terminal_class
windowrule = workspace special:discord, match:class discord
windowrule = workspace special:whatsapp, match:class brave-web.whatsapp.com__-.*
windowrule = float on, workspace special:teamspeak3, match:class TeamSpeak 3
windowrule = float on, center on, workspace special:game, match:class gamescope
windowrule = float on, center on, workspace special:game, match:class steam_app_(.+)

# Floating windows
windowrule = float on, center on, size >1000 >1000, match:class org.pulseaudio.pavucontrol
