# disable webcam mic

monitor.alsa.rules = [
  {
    matches =[
      {
	alsa.card_name = "Logitech BRIO",
	media.class = "Audio/Source"
      }
    ],
    actions = {
      update-props = {
	node.disabled = true
      }
    }
  }
]
