# disable sinks and change nickname
monitor.alsa.rules = [
  {
    matches = [
      {
	alsa.card_name = "Samson Q2U Microphone",
	media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
  {
    matches = [
      {
	alsa.card_name = "Samson Q2U Microphone",
	media.class = "Audio/Source"
      }
    ]
    actions = {
      update-props = {
        node.nick = "Samson Q2U"
        node.description = "Samson Q2U"
	device.form_factor = "microphone"
	device.icon_name = "audio-microphone"
      }
    }
  }
]
